name: "wav2vec2"
backend: "onnxruntime"
max_batch_size: 0
input: [
  {
    name: "audio"
    data_type: TYPE_FP32
    dims: [ 1, -1]
  }
]
output: [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [ 1, -1, 110 ]
  }
]